---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cert-manager-issuer
  namespace: flux-system
spec:
  dependsOn:
  - name: cert-manager
  interval: 5m0s
  path: ./cert-manager-issuer
  prune: true
  sourceRef:
    kind: GitRepository
    name: civo-workshop
  targetNamespace: default

