---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./cert-manager
  prune: true
  sourceRef:
    kind: GitRepository
    name: civo-workshop
  targetNamespace: default

