---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: ingress-nginx
  namespace: default
spec:
  interval: 60m
  url: https://kubernetes.github.io/ingress-nginx
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: default
spec:
  interval: 60m
  releaseName: ingress-nginx
  chart:
    spec:
      chart: ingress-nginx
      version: 4.2.3
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
      interval: 10m
  values:
    controller:
      metrics:
        enabled: true
        service:
          annotations:
            prometheus.io/port: "10254"
            prometheus.io/scrape: "true"
      service:
        annotations:
          external-dns.alpha.kubernetes.io/hostname: "*.user5.workshop.gimlet.io"
    defaultBackend:
      enabled: true
